paths:
  data_path: "C:/Users/fgrv/OneDrive/Documentos/PythonProjects/doctorado/\
    reinicio/asphalt-crack-segmentation"
  dataset_path: "C:/Users/fgrv/OneDrive/Documentos/PythonProjects/doctorado/\
    CrackDataset/luz_crack/"
  
training:
  save_model: true
  batch_size: 16
  learning_rate: 0.001
  encoder_lr_factor: 0.1
  num_epochs: 200
  weight_decay: 0.0001
  num_workers: 8
  model_save_path: "models/best_model.pth"
  log_interval: 10
  save_frequency: 5
  early_stopping_patience: 10
  accumulation_steps: 2
  mixed_precision: true  # Enable/disable mixed precision
  image_size: 384  # Image size output from Resize

  # Add scheduler configuration
  scheduler:
    type: "WarmupCosineAnnealing"
    warmup_epochs: 10  # Épocas de calentamiento
    min_lr_decoder: 0.00001  # LR mínimo para decoder después de annealing
    min_lr_encoder: 0.000001  # LR mínimo para encoder después de annealing

model:
  type: "swin2_unet"  # or unet, unet2, unet_resnet
  in_channels: 3   # Standardized parameter name
  out_channels: 1  # Standardized parameter name

  # Model specific configurations
  swin2_unet:  
    img_size: 384
    patch_size: 4
    embed_dim: 96
    depths: [2, 2, 6, 2]
    depths_decoder: [2, 2, 2, 2]
    num_heads: [3, 6, 12, 24]
    window_size: 12
    mlp_ratio: 4.0
    qkv_bias: true
    drop_rate: 0.0
    attn_drop_rate: 0.0
    drop_path_rate: 0.2
    ape: false
    patch_norm: true
    use_checkpoint: false
    pretrained_window_sizes: [0, 0, 0, 0]
    pretrained: true
    pretrained_model_path: "saved_models/swinv2_small_window16_256_in1k.pth"
    freeze_encoder: true
    decoder_dropout: 0.1
    unfreezing_patience: 5  # Epochs without improvement before unfreezing next stage

  unet:
    num_filters: 64
    encoder_dropout: 0.1
    bottleneck_dropout: 0.5
    decoder_dropout: 0.1

  loss:
    type: "combined"  # bce, dice, or combined
    bce_weight: 0.5
    dice_weight: 0.5
  
  # UNetResNet specific parameters
  unet_resnet:
    backbone: "resnet34"  # Options: "resnet18", "resnet34", "resnet50", "resnet101", "resnet152"
    pretrained: true
    freeze_encoder: true
    features: [256, 128, 64, 32]
    decoder_dropout: 0.1
    dropout_factor: 1.0
    unfreezing_patience: 5  # Epochs without improvement before unfreezing next stage

evaluation:
  metrics: 
    - iou
    - recall
    - precision
    - f1
  save_results: true
  results_save_path: "results/evaluation_results.json"